/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpskillRouteImport } from './routes/upskill'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ChampionsRouteImport } from './routes/champions'
import { Route as IndexRouteImport } from './routes/index'

const UpskillRoute = UpskillRouteImport.update({
  id: '/upskill',
  path: '/upskill',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsRoute = ChampionsRouteImport.update({
  id: '/champions',
  path: '/champions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/upskill': typeof UpskillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/upskill': typeof UpskillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/champions': typeof ChampionsRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/upskill': typeof UpskillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/champions' | '/discover' | '/explore' | '/upskill'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/champions' | '/discover' | '/explore' | '/upskill'
  id: '__root__' | '/' | '/champions' | '/discover' | '/explore' | '/upskill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChampionsRoute: typeof ChampionsRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  UpskillRoute: typeof UpskillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upskill': {
      id: '/upskill'
      path: '/upskill'
      fullPath: '/upskill'
      preLoaderRoute: typeof UpskillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions': {
      id: '/champions'
      path: '/champions'
      fullPath: '/champions'
      preLoaderRoute: typeof ChampionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChampionsRoute: ChampionsRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  UpskillRoute: UpskillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
