/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpskillRouteImport } from './routes/upskill'
import { Route as UnderstandRouteImport } from './routes/understand'
import { Route as IndexRouteImport } from './routes/index'

const UpskillRoute = UpskillRouteImport.update({
  id: '/upskill',
  path: '/upskill',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandRoute = UnderstandRouteImport.update({
  id: '/understand',
  path: '/understand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/understand': typeof UnderstandRoute
  '/upskill': typeof UpskillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/understand': typeof UnderstandRoute
  '/upskill': typeof UpskillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/understand': typeof UnderstandRoute
  '/upskill': typeof UpskillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/understand' | '/upskill'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/understand' | '/upskill'
  id: '__root__' | '/' | '/understand' | '/upskill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnderstandRoute: typeof UnderstandRoute
  UpskillRoute: typeof UpskillRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upskill': {
      id: '/upskill'
      path: '/upskill'
      fullPath: '/upskill'
      preLoaderRoute: typeof UpskillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understand': {
      id: '/understand'
      path: '/understand'
      fullPath: '/understand'
      preLoaderRoute: typeof UnderstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnderstandRoute: UnderstandRoute,
  UpskillRoute: UpskillRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
